### ISSUE TITLE
Use of enums in object declaration causes failure with --align-object-properties & TypeScript

### ISSUE THREAD

**Issue by systemmonkey42** [brody2consult/prettierx#692]
Tested with Prettierx version: `0.19.0` and `master (0.19.1-dev)`

The following code fragment
```
enum horses {
    draught,
    brumby,
    stock,
    calabrese,
    curly,
    clydesdale,
    cleveland,
}

const weight: { [key in horses]?: number } = {
    [horses.draught]: 320,
    [horses.brumby]: 900,
    [horses.clydesdale]: 1200,
};
```
Causes prettierX to fail when the `--align-object-properties` option is set.

```
brodybits@brodybits-mini-mac-book prettierx % ./bin/prettierx.js --align-object-properties info.ts                    
info.ts[error] info.ts: TypeError: Cannot read property 'raw' of undefined
[error]     at getPropertyPadding (/Users/brodybits/prettierx/src/language-js/print/property.js:144:20)
[error]     at AstPath.call (/Users/brodybits/prettierx/src/common/ast-path.js:66:20)
[error]     at printProperty (/Users/brodybits/prettierx/src/language-js/print/property.js:186:32)
[error]     at printPathNoParens (/Users/brodybits/prettierx/src/language-js/printer-estree.js:374:14)
[error]     at Object.genericPrint [as print] (/Users/brodybits/prettierx/src/language-js/printer-estree.js:90:19)
[error]     at callPluginPrintFunction (/Users/brodybits/prettierx/src/main/ast-to-doc.js:133:21)
[error]     at mainPrintInternal (/Users/brodybits/prettierx/src/main/ast-to-doc.js:76:17)
[error]     at mainPrint (/Users/brodybits/prettierx/src/main/ast-to-doc.js:56:14)
[error]     at /Users/brodybits/prettierx/src/language-js/print/object.js:122:18
[error]     at AstPath.each (/Users/brodybits/prettierx/src/common/ast-path.js:95:7)
brodybits@brodybits-mini-mac-book prettierx % ./bin/prettierx.js --align-object-properties --parser=typescript info.ts
info.ts[error] info.ts: TypeError: Cannot read property 'raw' of undefined
[error]     at getPropertyPadding (/Users/brodybits/prettierx/src/language-js/print/property.js:144:20)
[error]     at AstPath.call (/Users/brodybits/prettierx/src/common/ast-path.js:66:20)
[error]     at printProperty (/Users/brodybits/prettierx/src/language-js/print/property.js:186:32)
[error]     at printPathNoParens (/Users/brodybits/prettierx/src/language-js/printer-estree.js:374:14)
[error]     at Object.genericPrint [as print] (/Users/brodybits/prettierx/src/language-js/printer-estree.js:90:19)
[error]     at callPluginPrintFunction (/Users/brodybits/prettierx/src/main/ast-to-doc.js:133:21)
[error]     at mainPrintInternal (/Users/brodybits/prettierx/src/main/ast-to-doc.js:76:17)
[error]     at mainPrint (/Users/brodybits/prettierx/src/main/ast-to-doc.js:56:14)
[error]     at /Users/brodybits/prettierx/src/language-js/print/object.js:122:18
[error]     at AstPath.each (/Users/brodybits/prettierx/src/common/ast-path.js:95:7)
```

Without the `--align-object-properties`, formatting works as usual.

Kind Regards

**Comment by brody2consult** [comment]
~~I tried this in my prettierX, works perfectly for me. Can you post some more info such as how you ran prettierX to help us get to the bottom of this?~~

---

Now reproduced with `--align-object-properties` (see below)

**Comment by systemmonkey42** [comment]
Thanks for trying this.

This clearly pointed to my configuration, so I culled my `.prettierrc` until I found the culprit.
```
{
  "alignObjectProperties": true
}
```
With this settings enabled, prettierx produces the error. 

Thanks again.

**Comment by brody2consult** [comment]
I just reproduced it with `--align-object-properties` & TypeScript in my work area, updated the title. I would be grateful if you can put this info into the original description as well.

Reproduced with both `babel-ts` (default prettierX parser for TypeScript) & `typescript` parsers.

```console
brodybits@brodybits-mini-mac-book prettierx % ./bin/prettierx.js --align-object-properties info.ts                    
info.ts[error] info.ts: TypeError: Cannot read property 'raw' of undefined
[error]     at getPropertyPadding (/Users/brodybits/prettierx/src/language-js/print/property.js:144:20)
[error]     at AstPath.call (/Users/brodybits/prettierx/src/common/ast-path.js:66:20)
[error]     at printProperty (/Users/brodybits/prettierx/src/language-js/print/property.js:186:32)
[error]     at printPathNoParens (/Users/brodybits/prettierx/src/language-js/printer-estree.js:374:14)
[error]     at Object.genericPrint [as print] (/Users/brodybits/prettierx/src/language-js/printer-estree.js:90:19)
[error]     at callPluginPrintFunction (/Users/brodybits/prettierx/src/main/ast-to-doc.js:133:21)
[error]     at mainPrintInternal (/Users/brodybits/prettierx/src/main/ast-to-doc.js:76:17)
[error]     at mainPrint (/Users/brodybits/prettierx/src/main/ast-to-doc.js:56:14)
[error]     at /Users/brodybits/prettierx/src/language-js/print/object.js:122:18
[error]     at AstPath.each (/Users/brodybits/prettierx/src/common/ast-path.js:95:7)
brodybits@brodybits-mini-mac-book prettierx % ./bin/prettierx.js --align-object-properties --parser=typescript info.ts
info.ts[error] info.ts: TypeError: Cannot read property 'raw' of undefined
[error]     at getPropertyPadding (/Users/brodybits/prettierx/src/language-js/print/property.js:144:20)
[error]     at AstPath.call (/Users/brodybits/prettierx/src/common/ast-path.js:66:20)
[error]     at printProperty (/Users/brodybits/prettierx/src/language-js/print/property.js:186:32)
[error]     at printPathNoParens (/Users/brodybits/prettierx/src/language-js/printer-estree.js:374:14)
[error]     at Object.genericPrint [as print] (/Users/brodybits/prettierx/src/language-js/printer-estree.js:90:19)
[error]     at callPluginPrintFunction (/Users/brodybits/prettierx/src/main/ast-to-doc.js:133:21)
[error]     at mainPrintInternal (/Users/brodybits/prettierx/src/main/ast-to-doc.js:76:17)
[error]     at mainPrint (/Users/brodybits/prettierx/src/main/ast-to-doc.js:56:14)
[error]     at /Users/brodybits/prettierx/src/language-js/print/object.js:122:18
[error]     at AstPath.each (/Users/brodybits/prettierx/src/common/ast-path.js:95:7)
```

**Comment by Yikes2000** [comment]
Fixed here ... https://github.com/brodybits/prettierx/pull/700
